apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ah
  namespace: argocd
  labels:
spec:
  project: robusta
  source:
    helm:
      valueFiles:
      - values.yaml  
    repoURL: https://github.com/ahmedgmansour/Robusta-helm.git
    targetRevision: main
    path: drupal/drupal7
    plugin:
      name: argocd-vault-plugin-helm   
  destination:
    server: https://kubernetes.default.svc
    namespace: dev