apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: dev
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: postgres
        image: registry.eu-central-1.harbor.vodafone.com/vf-ie-apps-for-good-tozi/docker-vfie-tozi-local/redis:latest
        # command:
        # - sleep
        # - "3600"
      imagePullSecrets:
      - name: regcred


     
