apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-secret
  namespace: argocd
  labels:
spec:
  project: robusta
  source: 
    repoURL: 'https://github.com/ahmedgmansour/Robusta-helm.git'
    targetRevision: HEAD
    path: argo
    plugin:
      name: argocd-vault-plugin-helm
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev